//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBackend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_googleshopping_product_status
    {
        public int product_id { get; set; }
        public int store_id { get; set; }
        public string product_variation_id { get; set; }
        public string destination_statuses { get; set; }
        public string data_quality_issues { get; set; }
        public string item_level_issues { get; set; }
        public int google_expiration_date { get; set; }
    }
}
