//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBackend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_googleshopping_target
    {
        public long advertise_google_target_id { get; set; }
        public int store_id { get; set; }
        public string campaign_name { get; set; }
        public string country { get; set; }
        public decimal budget { get; set; }
        public string feeds { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public int roas { get; set; }
    }
}
